# Generated by Django 3.2.25 on 2025-02-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Education', 'Education'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Select Category', 'Select Category'), ('Others', 'Others'), ('Hospital', 'Hospital')], default='Select Category', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=300)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
