# Generated by Django 3.2.25 on 2025-02-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Select Category', 'Select Category'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Hospital', 'Hospital'), ('Others', 'Others'), ('Necessities', 'Necessities'), ('Education', 'Education')], default='Select Category', max_length=100),
        ),
    ]
