# Generated by Django 3.2.25 on 2025-03-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Food', 'Food'), ('Shopping', 'Shopping'), ('Others', 'Others'), ('Education', 'Education'), ('Hospital', 'Hospital'), ('Necessities', 'Necessities')], default=None, max_length=100),
        ),
    ]
