# Generated by Django 3.2.25 on 2025-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0005_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Hospital', 'Hospital'), ('Travel', 'Travel'), ('Necessities', 'Necessities'), ('Others', 'Others'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Food', 'Food')], default=None, max_length=100),
        ),
    ]
