# Generated by Django 3.2.25 on 2025-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_manager', '0006_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Others', 'Others'), ('Hospital', 'Hospital'), ('Food', 'Food'), ('Education', 'Education')], default=None, max_length=100),
        ),
    ]
