# Generated by Django 3.2.25 on 2025-04-09 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money_manager', '0007_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Education', 'Education'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Travel', 'Travel'), ('Others', 'Others'), ('Hospital', 'Hospital')], default=None, max_length=100),
        ),
    ]
